name = "Simpleness"
license = "public domain"
licenselink = "https://github.com/RainerChiang/simpleness/blob/master/LICENSE"
description = "Concise Hugo theme"
homepage = "https://github.com/RainerChiang/simpleness"
tags = ["blog"]
features = ["blog"]
min_version = "0.51"

[author]
  name = "RainerChiang"
  homepage = "https://github.com/RainerChiang"

[original.author]
  name = "Niklas Buschmann"
  homepage = "https://github.com/niklasbuschmann/"
